name: Standard

on:
  push:
    branches-ignore:
      - master
jobs:
  standard:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-standardrb
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        gem install standardrb
    - name: Run Standard
      run: standardrb
